import type { LiveArtifact } from '../liveTypes';

export function Output({ artifacts }: { artifacts: LiveArtifact[] }) {
  return <section className="output-surface" aria-labelledby="output-heading">
    <div className="output-heading"><div><p className="eyebrow">Project surface</p><h1 id="output-heading">Output</h1><p>Recent, important registered artifacts — not a general file browser.</p></div></div>
    <p className="derived-state" role="status">Canonicality and verification remain independent. Workbench shows only artifact registry facts and never opens a binary automatically.</p>
    {artifacts.length === 0 ? <div className="surface-empty"><h2>No registered outputs</h2><p>The active project has no artifact records. Nothing has been inferred from its filesystem.</p></div> : <ul className="output-gallery" aria-label="Artifact registry">{artifacts.map((artifact) => <li key={artifact.id}><article className={`artifact-tile artifact-medium-${artifact.kind}`}><div className="artifact-preview artifact-preview-binary" role="note"><p className="artifact-binary-glyph" aria-hidden="true">□</p><p className="artifact-binary-note">Registered artifact — metadata only. It is never opened or executed automatically.</p></div><div className="artifact-meta"><h3 dir="auto">{artifact.name}</h3><p className="artifact-badges"><span className={artifact.canonicality === 'canonical' ? 'artifact-badge is-canonical' : 'artifact-badge'}>{artifact.canonicality}</span><span className={`artifact-badge artifact-verification-${artifact.verification_state}`}>{artifact.verification_state}</span></p><dl className="artifact-technical"><dt>Kind</dt><dd>{artifact.kind}</dd><dt>Reference</dt><dd><bdi dir="ltr">{artifact.ref}</bdi></dd><dt>ID</dt><dd><bdi dir="ltr">{artifact.id}</bdi></dd></dl></div></article></li>)}</ul>}
  </section>;
}
